### ISSUE TITLE
InsecurePlatformWarning

### ISSUE THREAD

**Issue by intchloe** [DonnchaC/cloudflare-tor-whitelister#3]
Hello,

I get the following error:

/usr/local/lib/python2.7/dist-packages/requests-2.6.1-py2.7.egg/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
Traceback (most recent call last):
  File "./cloudflare-whitelist.py", line 326, in <module>
    main()
  File "./cloudflare-whitelist.py", line 181, in main
    res = r.json()
  File "/usr/local/lib/python2.7/dist-packages/requests-2.6.1-py2.7.egg/requests/models.py", line 819, in json
    return json.loads(self.text, **kwargs)
  File "/usr/lib/python2.7/json/**init**.py", line 326, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 365, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 383, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

Latest Debian from Digitalocean.

**Comment by DonnchaC** [comment]
Sorry for the delay in getting back to you. This is an warning raised by the python Requests package when only the stock SSL libraries are available. Installing the following packages should resolve the issue.

```
apt-get install python-dev libffi-dev libssl-dev
pip install 'requests[security]'
```

More information about the issue is available on Stack Exchange at https://stackoverflow.com/questions/29099404/ssl-insecureplatform-error-when-using-requests-package
